#ifndef PHYSICS_CONSTANTS_H
#define PHYSICS_CONSTANTS_H

#define CONTACT_BETA 0.2f
#define CONTACT_SOLVE_ITERATIONS 10

#define GRAVITATIONAL_CONSTANT 2000

#define DEFAULT_BALL_RESTITUTION 0.9f
#define DEFAULT_BALL_FRICTION 0.7f

#define DEFAULT_WALL_RESTITUTION 0.9f
#define DEFAULT_WALL_FRICTION 0.7f

#endif
